sudo: required

language: node_js

node_js:
  - "8.9.4"

services:
  - docker

before_install:
- docker-compose -f docker-compose-test.yml -p test build

script:
- docker-compose -f docker-compose-test.yml -p test run --rm --entrypoint 'npm test' web
